### ISSUE TITLE
Error sending request from client 

### ISSUE THREAD

**Issue by fkleedorfer** [fkleedorfer/aic2014#54]
When using the new 
!bomb N
command from the OnionClientApp, if N is large enough, this exception will occur sooner or later:

```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://127.0.0.1:51219/request":Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:584)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:356)
	at com.github.aic2014.onion.client.OnionClient.executeOnionRoutedHttpRequest(OnionClient.java:69)
	at com.github.aic2014.onion.client.OnionClientCommandLineRunner$1.run(OnionClientCommandLineRunner.java:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:790)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1534)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:48)
	at org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33)
	at org.springframework.web.client.DefaultResponseErrorHandler.getHttpStatusCode(DefaultResponseErrorHandler.java:56)
	at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:50)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569)
	... 7 more
```

**Comment by fkleedorfer** [comment]
Fixed.
Things like this happen when the network gets congested. The trick is not to allow more traffic into each chainnode than it can handle internally. This means, the number of concurrent tomcat threads must be smaller than the number of threads available to the internal ThreadExecutor.
